# Generated by Django 5.1.5 on 2025-02-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_media_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10, null=True),
        ),
    ]
