# Generated by Django 5.1.5 on 2025-02-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_media_media_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='album',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
