# Generated by Django 5.1.5 on 2025-02-05 13:25

import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_album_options_rename_created_album_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to=gallery.models.media_upload_path),
        ),
    ]
